#======method setting======
model:
  framework: vlm_single_label #vlm or vm
  method: clip_c2c
  text_encoding_manner: component #composition, component, c2c_vanilla, c2c_enhance
  backbone: "ViT-B/16"
  pred_mode: both
  prompt_learn_method: coop
  
  # CPR
  use_CPR: True
  CPR_aug_prob: 0.95
  CPR_alpha: 2.0
  CPR_lambda: 0.5  
  CPR_OW_com_loss_scale : 1.0
  CW_com_loss_scale : 0.0
  use_FAME: True
  fame_beta: 0.4

  use_cooc_penalty: True
  cooc_penalty_loss_scale: 0.5
  train_cooc_threshold: 1.0
  cooc_penalty_margin: 0.5
  cooc_penalty_loss_scale_start: 15
  cooc_penalty_loss_scale_end: 15
  cooc_mask_type: p_v_o_on_o_and_v

  # TORC
  temporal_modeling_shuffle: True
  temporal_modeling_shuffle_type: cosine_entropy
  temporal_modeling_shuffle_loss_scale: 1.0
  penalty_loss_scale_start: 5
  penalty_loss_scale_end: 10

  # FSP & FCP 
  val_with_confusion : True



text:
  text_input_type: template 
  input_template: "An action of which the dominating object is x and the verb is x" 
  input_template_verb: "A verb of  x" 
  input_template_obj: "An object of  x" 
  input_template: "a photo of x" 
  learn_input: true 
  learn_input_method: zero
  verb_length_type: natural
  ctx_init: true 
  #===train===
  text_lr: 0.0001
  text_wd: 0.00001
  ctx_length: 77


data:
  dataset: sth-com
  #set as your own path
  dataset_path: YOUR_DATASET_PATH
  num_frames: 16
  num_workers: 6

#======compositional module setting======
c2c:
  nlayers: 2
  fc_emb: 768,1024,1200
  feat_dim: 512
  emb_dim: 512
  relu: False

#======visual encoder setting======
visual:
  pretrained: CLIP
  num_frames: 16
  adapt_star_layer: 6
  num_tadapter: 2
  num_workers: 8
  cosine_scale: 14
  visual_lr: 0.0005
  visual_wd: 0.0001

code_adapt:
  arch: vit
  aux_input: False
  ade_input: False


#======general training setting======
train:
  train_batch_size: 16
  gradient_accumulation_steps: 1
  seed: 0
  epochs: 40
  val_epochs_ts: 45
  warmup: 3
  epoch_start: 0
  save_path: YOUR_LOG_PATH
  load_model: False
  best_model_metric: hm_comp_acc  
  eval_every_n: 1
  save_every_n: 3
  val_start_epoch: 0
  aux_input: False
  ade_input: False

test:
  eval_batch_size: 32
  open_world: False
  topk: 1
  text_encoder_batch_size: 32
  bias: 0.001
  pretrain: False
  load_model:  YOUR_PATH